### ISSUE TITLE
MongoDb connection(Learning)

### ISSUE THREAD

**Issue by nithyabz** [Being-Zero/stopstalk-mern#1]
**Connection of mongoDB to Django project**
https://docs.google.com/document/d/1D7_BZ20h6FCdui98yWdqQQ32rkBVENUtKeh9F2FYGhs/edit?usp=sharing

**Connection of mongoDB to frontend using express.js(in progress)**
https://docs.google.com/document/d/1xEMmqruMKrVOkCYlE3opP2OhSHr4Ip559rIcICcxtX0/edit

**Comment by kaushikkumarbz** [comment]
1. Create a Nodejs project and connect Mongodb to it
